// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZALZVhpwuPcHlRIevG2VA0lGbDZ4I61s',
    appId: '1:304704218262:web:111e0c388ecc561be6ceb7',
    messagingSenderId: '304704218262',
    projectId: 'psi-book-store-e75a3',
    authDomain: 'psi-book-store-e75a3.firebaseapp.com',
    storageBucket: 'psi-book-store-e75a3.firebasestorage.app',
    measurementId: 'G-75SETDBMK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC00pnOJMEx2538xuaY2PUFixnloKboQXg',
    appId: '1:304704218262:android:bb41a577f0612536e6ceb7',
    messagingSenderId: '304704218262',
    projectId: 'psi-book-store-e75a3',
    storageBucket: 'psi-book-store-e75a3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZALZVhpwuPcHlRIevG2VA0lGbDZ4I61s',
    appId: '1:304704218262:web:02ef2c407514c923e6ceb7',
    messagingSenderId: '304704218262',
    projectId: 'psi-book-store-e75a3',
    authDomain: 'psi-book-store-e75a3.firebaseapp.com',
    storageBucket: 'psi-book-store-e75a3.firebasestorage.app',
    measurementId: 'G-1PNZ5Q6GVX',
  );
}
