"""Domain constants for the extended online bookstore."""

ROLE_ADMIN = "ADMIN"
ROLE_SHOP_OWNER = "SHOP_OWNER"
ROLE_CUSTOMER = "CUSTOMER"
ROLE_DELIVERY_AGENT = "DELIVERY_AGENT"

ALL_ROLES = {
    ROLE_ADMIN,
    ROLE_SHOP_OWNER,
    ROLE_CUSTOMER,
    ROLE_DELIVERY_AGENT,
}

USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_BLOCKED = "BLOCKED"

ORDER_STATUS_PLACED = "PLACED"
ORDER_STATUS_CONFIRMED = "CONFIRMED"
ORDER_STATUS_PACKED = "PACKED"
ORDER_STATUS_SHIPPED = "SHIPPED"
ORDER_STATUS_OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
ORDER_STATUS_DELIVERED = "DELIVERED"

ORDER_LIFECYCLE = [
    ORDER_STATUS_PLACED,
    ORDER_STATUS_CONFIRMED,
    ORDER_STATUS_PACKED,
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_OUT_FOR_DELIVERY,
    ORDER_STATUS_DELIVERED,
]

DELIVERY_TYPE_LOCAL = "LOCAL"
DELIVERY_TYPE_COURIER = "COURIER"
DELIVERY_TYPES = {DELIVERY_TYPE_LOCAL, DELIVERY_TYPE_COURIER}

DELIVERY_STATUS_ASSIGNED = "ASSIGNED"
DELIVERY_STATUS_PICKED_UP = "PICKED_UP"
DELIVERY_STATUS_OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
DELIVERY_STATUS_DELIVERED = "DELIVERED"
DELIVERY_STATUSES = {
    DELIVERY_STATUS_ASSIGNED,
    DELIVERY_STATUS_PICKED_UP,
    DELIVERY_STATUS_OUT_FOR_DELIVERY,
    DELIVERY_STATUS_DELIVERED,
}

COURIER_STATUS_SHIPPED = "SHIPPED"
COURIER_STATUS_IN_TRANSIT = "IN_TRANSIT"
COURIER_STATUS_REACHED_DESTINATION = "REACHED_DESTINATION"
COURIER_STATUS_OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
COURIER_STATUS_DELIVERED = "DELIVERED"
COURIER_STATUSES = {
    COURIER_STATUS_SHIPPED,
    COURIER_STATUS_IN_TRANSIT,
    COURIER_STATUS_REACHED_DESTINATION,
    COURIER_STATUS_OUT_FOR_DELIVERY,
    COURIER_STATUS_DELIVERED,
}

ADMIN_COMMISSION_RATE = 0.10
